### PR TITLE
New cards, update to utility.lua

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by EerieCode** [comment]
The procedures I've added to the utilities will let you add all base functions required for Union monsters with a single function, similar to how it's done with Pendulum and Gemini monsters. I've added many optional parameters to EnableUnionAttribute() to make it work even with older monsters (ex. monsters that force to have only 1 Union monster, monsters that can only be Summoned in certain positions, etc.). "aux.IsUnionEquipped" can be put in SetCondition() to check if a monster is Union equipped, similar to aux.IsDualState for Gemini monsters. I've tested these functions on "Torque Tune Gear", they work without issues.

**Comment by Ygoproco** [comment]
Sorry we had some bad experiences with changes to utility.lua. Please don't modify it unless absolutely necessary.

**Comment by EerieCode** [comment]
I did some tests with the new utility.lua specifically to ensure there wouldn't be any problems, but I can see your point. In this case, should I close this branch and remake "Torque Tune Gear" without using the new utilities?

**Comment by Ygoproco** [comment]
Yes would be great if you could do that.

**Comment by EerieCode** [comment]
Ok. For the record, though, I might need to do some changes to utility.lua in the near future anyway: Steel asked me to look into some bugs with the Kaiju cards, and it's more than likely I'll have to edit their procedures in that file.

**Comment by Steeldarkeagel** [comment]
If you add a note to that one EerieCode saying you have changed it and you want me to test it as well, I can download it separately and do a bunch of tests to make sure it works first.

**Comment by EerieCode** [comment]
For the Kaijus or for the Unions? I haven't finished the former yet, but for the latter they are all the functions after line 1647 (EnableUnionAttribute(), UnionEqFilter(), UnionEqTarget(), IsUnionEquipped(), UnionSpTarget(), UnionSpOperation() and UnionReplace()). "Torque Tune Gear" uses them already, I can PM you the errata'd versions of Kaiba's Union monsters if you need them.

**Comment by Steeldarkeagel** [comment]
If you have to change utility for anything just make a note on it or PM me or both and I can try to do a long check of it to make sure it does not break it like it has done before.

**Comment by EerieCode** [comment]
Understood. I'll PM you the altered script for any future changes then. So, do I close this branch or can I leave it open for now?

**Comment by Steeldarkeagel** [comment]
Close it for now and make a new one without changing the utilities, we can look into updating utilities with the next major update.

**Comment by EerieCode** [comment]
Ok. I'll reupload the script for the new card without the utilities, then.

**Pull request closed without merging**
