### PR TITLE
Added "Odd-Eyes Persona Dragon"

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by Steeldarkeagel** [comment]
Do you have a source to clarify this, except for http://yugioh.wikia.com/wiki/Odd-Eyes_Persona_Dragon?
I can't find any other source?

**Comment by EerieCode** [comment]
Not really, unfortunately: I was surprised to see it myself. That said, the
effect is consistent with the manga version, so it's at least likely to be
accurate.

2016-03-07 21:39 GMT+01:00 Steeldarkeagel notifications@github.com:

**Comment by Steeldarkeagel** [comment]
Do you mind if we wait a little while for this? I would like to see a little clarification on it first? Wish the wikia would provide sources >.<

**Comment by EerieCode** [comment]
No problem for me, I'm curious about it myself: it coems out in 12 days
anyway, so it's going to come out on Twitter soon. It's strange, though:
I'm following both the Organization and Maxut, and none of them ever
reported anything about it.

2016-03-07 21:42 GMT+01:00 Steeldarkeagel notifications@github.com:

**Comment by Steeldarkeagel** [comment]
If you or someone else reading this finds a source post it so we can see.

**Comment by EerieCode** [comment]
We have a source at this link.

http://blog.livedoor.jp/maxut/archives/47034883.html

The Japanese text matches the one on the Wikia, and the picture on that
page appears to be an high quality scan of the page at the link: it should
be enough to validate it.

**Pull request merged**
