### PR TITLE
Fixed Divine Serpent Geh

### PR DESCRIPTION
**Pull request by kenpazaraki**

### CODE REVIEW

**Comment by LorisC93** [comment]
you are using an old version of the script, and the battle problem you said doesn't exist anymore, I summoned him just now after a battle destruction without problems.

Try this version and you'll see it works: https://github.com/YgoPro-Sahim/Live/blob/d37c8683eca4e06794a9583d770d2eb8c1f6551d/script/c6132.lua

**Comment by kenpazaraki** [comment]
The problem with your version is not that it doesn't work when it should, but that it works when it shouldn't, since it allows to special summon Geh when I attack and my monster gets destroyed.

**Comment by LorisC93** [comment]
..... I understood the problem only now!
it says "by your opponent's attack", I hadn't properly read that part!

Anyway you are using an old version of the script, I fixed some other minor problems in the meantime.

**Comment by LorisC93** [comment]
Look at my last fix, do you think it solves the problem?
If yes I think it's a bit easier to understand.

**Comment by kenpazaraki** [comment]
I tested both versions and they both work fine. I'll close my pull request to avoid potential conflicts.

**Comment by LorisC93** [comment]
I'll add credits to you to my commit, you helped a lot!

**Pull request closed without merging**
