### PR TITLE
added "Lullaby of Obedience", "Union Hangar", "Scramble Union" & "AtoZ-Dragon Buster Cannon"

### PR DESCRIPTION
**Pull request by LorisC93**

### CODE REVIEW

**Comment by EerieCode** [comment]
I think there are a few problems with the script:
- The declaration of a card name must happen in the target function, not in the operation function: otherwise the opponent wouldn't be able to respond to it with cards like "Engraver of the Seal".
- You can only declare monsters for this card, but there are no such restrictions in the script: it should be something like Duel.AnnounceCard(tp,TYPE_MONSTER), like with "Dark Designator".

**Comment by LorisC93** [comment]
My "Dark Designator" code has "local code=Duel.AnnounceCard(tp)", without TYPE_MONSTER, I didn't know it was possible to limit the choice to monsters!

**Comment by LorisC93** [comment]
Effectively it works! Moved the declaration to Target and added the restriction.

**Comment by EerieCode** [comment]
I see no issues with "Lullaby" now. As for "Union Hangar":
- You don't have to use 2 EFFECT_TYPE_ACTIVATE: keep only the second, set chk==0 always true so that it can always be activated, and then in .operation make it so that, is there is a valid card, Duel.SelectYesNo() asks whether the player wants to add it. "Oracle of Zefra" is similar, but with a mandatory effect: you can use that as the base.
- I'm not familiar with Union cards, so I can't say at first glance if there's something wrong with the last effect: if it works while testing, then it should be fine.

**Comment by LorisC93** [comment]
ook, that can be easily changed.

**Comment by EerieCode** [comment]
Okay, they should be all correct now.

**Comment by LorisC93** [comment]
eheh, thank you for your help!

**Comment by EerieCode** [comment]
No problem!

**Pull request merged**
