### PR TITLE
New cards

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by kenpazaraki** [comment]
Thank you for the new cards! There are a few bugs, though:
1) Quan: can't activate its effect (35: Parameter 3 should be "Group")
2) Ametrix: doesn't float (59: Parameter 1 should be "Function"), it's possible that Quandam has the same bug
3) Citri: shouldn't Special Summon from the opponent's Graveyard

**Comment by EerieCode** [comment]
Thanks! I can upload a fix for the latter two (three, if we count Quandam)
in a few minutes, but I'll have to do some test on Quon to figure out its
problem and I have no time for it ATM. I'll upload a patch for it tomorrow.

2016-06-24 22:32 GMT+02:00 kenpazaraki notifications@github.com:

**Comment by EerieCode** [comment]
Ok, the fixed versions are up. The only one missing is Quon, I'll work on it tomorrow.

**Comment by kenpazaraki** [comment]
Thanks! Once the PR gets accepted, I'll see if I can manage to fix Quon myself.

**Pull request merged**
