### PR TITLE
Added "ABC-Dragon Buster"

### PR DESCRIPTION
**Pull request by LorisC93**

### CODE REVIEW

**Comment by LorisC93** [comment]
is there a way to exclude the "Merge remote-tracking branch" actions from the pulls?
I haven't figured out how to do!

**Comment by mercury233** [comment]
Don't use master branch to do pull request.

**Comment by LorisC93** [comment]
So I have to create another branch, do the edits and pull from it, right?

**Comment by mercury233** [comment]
I usually do this in my fork:

git fetch https://github.com/Ygoproco/Live
git checkout FETCH_HEAD
git checkout -b patch-1
git commit
git push origin patch-1

**Pull request merged**
