### PR TITLE
added "Delta The Magnet Warrior"

### PR DESCRIPTION
**Pull request by LorisC93**

### CODE REVIEW

**Comment by EerieCode** [comment]
I think the first effect is missing an EFFECT_FLAG_DELAY, since it's an "if" effect: also, in the Special Summon effect, 'e1:SetCountLimit(1,6142)' should be 'e3:SetCountLimit(1,6142+1)'. Aside from that, it should be alright: I've just uploaded the picture on the repository, it should be approved soon.

**Comment by LorisC93** [comment]
Thanks! I'll edit it as soon as I can

**Comment by LorisC93** [comment]
I had too much hurry when I uploaded it

**Comment by LorisC93** [comment]
I have edited it using my cellphone, I hope to not have done disasters!

**Comment by EerieCode** [comment]
Don't worry, everything seems alright now!

**Pull request merged**
