### PR TITLE
Added warning about unconfirmed effects, bug fixes

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by Zayelion** [comment]
Could you port some of these over to the main ygopro-pre-script repo please?

**Comment by EerieCode** [comment]
I should be able to do it in a few hours.

2016-04-20 7:42 GMT+02:00 Jamezs Gladney notifications@github.com:

**Comment by Zayelion** [comment]
Much appreciated ^_^

**Comment by EerieCode** [comment]
Ok, I've added the Cubic monsters to the repository (with your style of numeration, of course. Thank goodness it takes 5 seconds of Find&Replace to do it!). Let's just hope those fixes are enough!

**Comment by Zayelion** [comment]
Thanks!

**Pull request merged**
