### PR TITLE
Added "Divine Serpent Geh"

### PR DESCRIPTION
**Pull request by LorisC93**

### CODE REVIEW

**Comment by kenpazaraki** [comment]
It should be possible to activate the e6 effect only once per chain, but the code is missing that part, so it'll end up as an effect that can be activated in response to itself, potentially creating an infinite chain.

**Comment by LorisC93** [comment]
That's right, but I think that a SetCountLimit set to 1 it may be wrong is some particular situations.
I'm searching for a good solution!

**Comment by LorisC93** [comment]
Ook, found it!

**Comment by kenpazaraki** [comment]
That should work, but there's another thing that might give problems. The part about its summoning conditions doesn't check who controls the destroyed monster, so it would be possible to special summon it when an opponent's monster is destroyed.

**Comment by LorisC93** [comment]
I was sure I included that part, I'll check

**Comment by LorisC93** [comment]
It's present, c:GetPreviousControler()==tp should do that part.

**Comment by kenpazaraki** [comment]
The problem is that it applies only if the monster is destroyed by effects, but it doesn't work if it's destroyed by battle.

EDIT: If you copy and paste that part next to c:IsReason(REASON_BATTLE) it should work properly.

**Comment by LorisC93** [comment]
you are right!

**Comment by kenpazaraki** [comment]
Next to c:IsReason(REASON_BATTLE) there should be a piece of code that checks whose turn it is, otherwise it would be possible to summon Geh during both players' turn.

EDIT: Also, the effect that lets Geh change its attack should work when it attacks directly too.

**Comment by LorisC93** [comment]
It must be possible to summon him during both player turns, and the effect that changes Geh's ATK works only if it battles, so with another monster

**Comment by kenpazaraki** [comment]
About the 1st part, that's true only if it's summoned when a monster is destroyed by a card effect, not if it's destroyed by battle, since the opponent's monster must be attacking to trigger Geh. About the battle part, attacking an opponent directly is still considered battling: http://yugioh.wikia.com/wiki/Battle

**Comment by LorisC93** [comment]
I don't see the problem about the battle destruction! An opponent monster attacks, it destroys one of your monsters by battle, I can summon Geh, am I wrong?
Regarding the direct attack you're right!

**Comment by LorisC93** [comment]
*one of my monsters

**Comment by kenpazaraki** [comment]
You aren't wrong, but unless you changed the code already, Geh can be summoned after attacking a monster with one of your monster, not only when an opponent's monster attacks one of your monsters.

**Pull request merged**
