### PR TITLE
Added "A-Assault Core"

### PR DESCRIPTION
**Pull request by LorisC93**

### CODE REVIEW

**Comment by EerieCode** [comment]
The database prerelease.cdb is reserved for promo cards. I'd recommend closing this pull and creating a new one using an entirely new database, preferably called "prerelease-sdks.cdb" for "Structure Deck: Kaiba Seto": this way it'll be easier for Percy to integrate them later.

**Comment by Steeldarkeagel** [comment]
Also a picture in the Live-Images Git would be needed.

**Comment by EerieCode** [comment]
I guess you'll have to create it yourself for now, Sahim. I'd recommend you use [TCG Editor](http://www.tcgeditor.com/), it's one of the best editors. I can upload all other unofficial pictures tonight, it will make further scripting easier.

**Comment by LorisC93** [comment]
ook, I'll create a new pull with "prerelease-sdks.cdb" and will add the image too

**Pull request closed without merging**
