### PR TITLE
Added all VJump new cards

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by LorisC93** [comment]
Take a look at what I've done in my closed pull for "Neo Galaxy-Eyes Cipher Dragon", I may be useful to simplify your version.
I've seen that you have put a lot of conditions on the target part and I think it can be done without them.

**Comment by EerieCode** [comment]
You're right, that's a lot more efficient! Thank you! Give me a few minutes and I'll upload the new version.

**Comment by EerieCode** [comment]
Ok, with this it still works and it's more efficient and elegant. Thanks again!

**Comment by LorisC93** [comment]
Nice! After all we are here to help each other! To the next time!

**Comment by kenpazaraki** [comment]
OMK Gun's 1st effect doesn't seem to work. No idea why, though.

**Comment by EerieCode** [comment]
Weird, that's the first card I've tested. Does it give an error message? Did you take battle or effect damage?

**Comment by kenpazaraki** [comment]
No error message, sorry. It doesn't work with battle damage, idk about effect damage. Also, Ancient Gear Gadget has an error at line 100, there was a message about a nil value or something.

**Comment by EerieCode** [comment]
I'll doublecheck OMG Gum, but "Ancient Gear Gadget"'s issue is literally impossible: it doesn't even _have_ a line 100! [Look at it](https://github.com/EerieCode/Live/blob/075eb2f731d537de91e5294bfc00212408337007/script/c7450.lua), it ends at 95!

**Comment by kenpazaraki** [comment]
Lol. Maybe the error message had something to do with the AI.

**Comment by kenpazaraki** [comment]
Found out what the problem was. It was actually line 100 In Ancient Gear Hydra's script
screenshot 79

**Comment by EerieCode** [comment]
In that case, I think I've already found what the problem is: the patch I've just uploaded should take care of it. Thanks!

**Pull request merged**
