### PR TITLE
Added some new cards

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by mercury233** [comment]
If utility.lua was updated (https://github.com/Fluorohydride/ygopro-scripts/commit/85f61366807b0fc0e2bb6f57ae2e3e58dadfaea0), `aux.AddRitualProcGreaterCode` will automatic add `.material`. Or `aux.AddRitualProcGreaterCode` won't work.

**Comment by EerieCode** [comment]
I didn't know there was already an update in the utilities. So, how should
I change "Pre-Preparation of Rites"?

2015-12-20 10:33 GMT+01:00 Mercury233 notifications@github.com:

**Comment by mercury233** [comment]
I don't know if Percy's version updated utility.lua .
Here are my solution, used before my server update 1.033.8.
https://github.com/Daniel17173/ygopro/blob/master/unofficial/script/c5865.lua

**Comment by EerieCode** [comment]
Percy hasn't updated the file, so the Ritual procedure doesn't add
anything. Should we contact Percy and ask him about it? The codes I've
added to the cards work, I've already tested them, but we should probably
see what he thinks about it.

2015-12-20 10:38 GMT+01:00 Mercury233 notifications@github.com:

**Comment by mercury233** [comment]
Are you sure those rirual magic cards still work?

**Comment by EerieCode** [comment]
Yes. I've only added two attributes, they don't impact the other effects
and are only used by "Pre-Preparation of Rites".

2015-12-20 10:44 GMT+01:00 Mercury233 notifications@github.com:

**Comment by mercury233** [comment]
So **your** utility.lua and ritual magic cards is the updated version already. But the users may don't have it updated.

**Comment by EerieCode** [comment]
I haven't even touched the utility. I've only changed the Ritual Spells,
and those changes are included in the commit: my utility.lua is the same as
all the other users'.

2015-12-20 10:54 GMT+01:00 Mercury233 notifications@github.com:

**Comment by mercury233** [comment]
So there are no need to change all Ritual Spells again, just use the `mt.material_count` and `mt.material` added automaticly by `aux.AddRitualProcGreaterCode`.
https://github.com/Fluorohydride/ygopro-scripts/commit/85f61366807b0fc0e2bb6f57ae2e3e58dadfaea0#diff-e2dcb2b3468cae90b8ab3113481f4879R1197

**Comment by EerieCode** [comment]
That procedure is not in Ygopro Percy: it's not in the online folder, and
it's not in the utility file after the last update. Without that, the cards
have to be manually changed.

2015-12-20 10:59 GMT+01:00 Mercury233 notifications@github.com:

**Comment by mercury233** [comment]
If an user didn't updated utility.lua, `aux.AddRitualProcGreaterCode` won't work. So pushing those scripts to users could introduce a bug.

**Comment by EerieCode** [comment]
I've double-checked the file, and turns out we were both wrong: this is how
the function looks like:

function Auxiliary.AddRitualProcGreaterCode(c,code1)
 if c.fit_monster==nil then
  local code=c:GetOriginalCode()
  local mt=_G["c" .. code]
  mt.fit_monster={code1}
 end
 Auxiliary.AddRitualProcGreater(c,Auxiliary.FilterBoolFunction(Card.IsCode,code1))
end

So, it seems that there's no need to change most of the cards, but the
variable for the ritual monsters is wrong. Can you reject my commit? I'll
make the necessary changes and reupload it. There might be still the need
to change some cards, though: some Ritual cards don't use any functions
from the utility, so in those case .fit_monster has to be added manually
(like "Red-Eyes Transmigration").

2015-12-20 11:06 GMT+01:00 Mercury233 notifications@github.com:

**Comment by mercury233** [comment]
I am not the admin of this repository. You can close this pull request on github.com.

**Comment by EerieCode** [comment]
Ok, thanks!

**Comment by Steeldarkeagel** [comment]
If you need any help or other files need to be changed just give me a poke on the forums or on here EerieCode.

**Comment by EerieCode** [comment]
Thanks, but I've managed to fix it. The new commit uses the attribute in
the utility file: I've just tested the card, it works without problems.

2015-12-20 11:28 GMT+01:00 Steeldarkeagel notifications@github.com:

**Pull request closed without merging**
