### PR TITLE
Updated utility.lua

### PR DESCRIPTION
**Pull request by Cute-Nekomimi**
Added pcall(dofile,"init.lua") to end of file, to facilitate some custom card scripting.

### CODE REVIEW

**Comment by EerieCode** [comment]
Out of curiosity, how does this work?

**Comment by Zayelion** [comment]
O.O Ow wow thats pretty initiative. init.lua could be something like speedworld; it would apply the effect and change the rules of the game some. The issue is it would apply to all games and there would really be no way to turn it off but to delete the file o.O;;;

**Comment by Cute-Nekomimi** [comment]
EerieCode : Basically when utility.lua is run, it will execute pcall(dofile,"init.lua"), which will read the file init.lua as lua code and execute the contents. The pcall ensures that any errors encountered while trying to run init.lua (such as the file not existing) will be discarded, which keeps utility.lua from breaking in the case of errors (again, such as the file not existing).

Zayelion : That is really not the intended purpose of this, the reason I want to add this is that so that it is possible to make custom lua libraries that can run before the cards are actually loaded, this is needed for things like custom implementations of Effect.CreateEffect (which needs to be added before any card actually calls Effect.CreateEffect), which can modify the created effect to add additional functionality. 

While utility.lua can be modified to do whatever it is that would be put in init.lua, since utility.lua is often overwritten on core updates, and live updates to it are even more problematic (any changes will be discarded whenever the program loads), I was hoping for a file that would be safe to include custom changes like that, where the end user doesn't have to worry about the file being overwritten.

**Comment by Cute-Nekomimi** [comment]
Any possibility of this change being accepted?

**Pull request merged**
