### PR TITLE
New cards and bug fixes

### PR DESCRIPTION
**Pull request by EerieCode**

### CODE REVIEW

**Comment by kenpazaraki** [comment]
Got a bit impatient and I started testing the new Chemical Beasts. Most of them work fine, except for Hy Dragon, that shouldn't increase its own attack when it gets its own effect, also Hydron Hawk should Special Summon in defense position. Anyway, thank you for the new cards!

EDIT: Phoenixion's effects can't be activated at all, apparently.

EDIT 2: A monster banished by Spark Field's effect doesn't come back.

EDIT 3: PSY-Frame Accelerator should be able to activate its effects when it's activated (flipped face-up).

**Comment by EerieCode** [comment]
I can't fix them right now, I'll upload the fixes tomorrow after the episode. Thanks!

**Comment by EerieCode** [comment]
Okay, "Accelerator" is fine now. I'll take care of the others tomorrow.

**Comment by kenpazaraki** [comment]
Thanks! Also, about Hy Dragon's bug, I got the bug wrong. The ATK change happens only when it normal summons itself again, but it doesn't work when another Chemical Beast is normal summoned from the hand or is summoned again while face-up. Basically it doesn't work when it should and vice versa.

**Pull request merged**
